<?php

namespace ContainerNixeQi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_Metadata_Document_MetadataFactory_CachedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.metadata.document.metadata_factory.cached' shared service.
     *
     * @return \ApiPlatform\Elasticsearch\Metadata\Document\Factory\CachedDocumentMetadataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/DocumentMetadataFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/CachedDocumentMetadataFactory.php';

        return $container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.cached'] = new \ApiPlatform\Elasticsearch\Metadata\Document\Factory\CachedDocumentMetadataFactory(($container->privates['api_platform.elasticsearch.cache.metadata.document'] ?? $container->load('getApiPlatform_Elasticsearch_Cache_Metadata_DocumentService')), ($container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.cat'] ?? $container->load('getApiPlatform_Elasticsearch_Metadata_Document_MetadataFactory_CatService')));
    }
}
