<?php

namespace ContainerNixeQi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_Metadata_Document_MetadataFactory_CatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.metadata.document.metadata_factory.cat' shared service.
     *
     * @return \ApiPlatform\Elasticsearch\Metadata\Document\Factory\CatDocumentMetadataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/DocumentMetadataFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/CatDocumentMetadataFactory.php';

        return $container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.cat'] = new \ApiPlatform\Elasticsearch\Metadata\Document\Factory\CatDocumentMetadataFactory(($container->privates['api_platform.elasticsearch.client'] ?? $container->load('getApiPlatform_Elasticsearch_ClientService')), ($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.attribute'] ?? $container->load('getApiPlatform_Elasticsearch_Metadata_Document_MetadataFactory_AttributeService')));
    }
}
