<?php

namespace ContainerNixeQi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_RequestBodySearchExtension_SortService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.request_body_search_extension.sort' shared service.
     *
     * @return \ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\SortExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.elasticsearch.request_body_search_extension.sort'] = new \ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\SortExtension(($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($container->privates['api_platform.elasticsearch.identifier_extractor'] ?? $container->load('getApiPlatform_Elasticsearch_IdentifierExtractorService')), ($container->privates['api_platform.metadata.property.metadata_factory.cached.legacy'] ?? $container->getApiPlatform_Metadata_Property_MetadataFactory_Cached_LegacyService()), ($container->privates['api_platform.resource_class_resolver'] ?? $container->getApiPlatform_ResourceClassResolverService()), ($container->privates['api_platform.elasticsearch.name_converter.inner_fields'] ?? $container->getApiPlatform_Elasticsearch_NameConverter_InnerFieldsService()), 'ASC');
    }
}
