<?php

namespace ContainerNixeQi8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_RequestBodySearchExtension_SortFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.request_body_search_extension.sort_filter' shared service.
     *
     * @return \ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\SortFilterExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.elasticsearch.request_body_search_extension.sort_filter'] = new \ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\SortFilterExtension(($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($container->privates['api_platform.filter_locator'] ?? $container->getApiPlatform_FilterLocatorService()));
    }
}
