<?php

namespace ContainerWuQL70c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_Metadata_Document_MetadataFactory_AttributeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.metadata.document.metadata_factory.attribute' shared service.
     *
     * @return \ApiPlatform\Elasticsearch\Metadata\Document\Factory\AttributeDocumentMetadataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/DocumentMetadataFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/AttributeDocumentMetadataFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/ConfiguredDocumentMetadataFactory.php';

        return $container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.attribute'] = new \ApiPlatform\Elasticsearch\Metadata\Document\Factory\AttributeDocumentMetadataFactory(($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.configured'] ?? ($container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.configured'] = new \ApiPlatform\Elasticsearch\Metadata\Document\Factory\ConfiguredDocumentMetadataFactory([]))));
    }
}
