<?php

namespace ContainerWuQL70c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_IdentifierExtractorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.identifier_extractor' shared service.
     *
     * @return \ApiPlatform\Core\Bridge\Elasticsearch\Api\IdentifierExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Elasticsearch/Api/IdentifierExtractorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Elasticsearch/Api/IdentifierExtractor.php';

        return $container->privates['api_platform.elasticsearch.identifier_extractor'] = new \ApiPlatform\Core\Bridge\Elasticsearch\Api\IdentifierExtractor(($container->privates['api_platform.identifiers_extractor.cached'] ?? $container->getApiPlatform_IdentifiersExtractor_CachedService()));
    }
}
