<?php

namespace ContainerWuQL70c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_RequestBodySearchExtension_ConstantScoreFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.request_body_search_extension.constant_score_filter' shared service.
     *
     * @return \ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\ConstantScoreFilterExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.elasticsearch.request_body_search_extension.constant_score_filter'] = new \ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\ConstantScoreFilterExtension(($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($container->privates['api_platform.filter_locator'] ?? ($container->privates['api_platform.filter_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [], []))));
    }
}
