<?php

namespace ContainerWuQL70c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_ClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.client' shared service.
     *
     * @return \Elasticsearch\Client
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php';

        return $container->privates['api_platform.elasticsearch.client'] = \Elasticsearch\ClientBuilder::fromConfig(['hosts' => $container->getParameter('api_platform.elasticsearch.hosts')]);
    }
}
