<?php

namespace ContainerWuQL70c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_Metadata_Document_MetadataFactory_ConfiguredService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.metadata.document.metadata_factory.configured' shared service.
     *
     * @return \ApiPlatform\Elasticsearch\Metadata\Document\Factory\ConfiguredDocumentMetadataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/DocumentMetadataFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Elasticsearch/Metadata/Document/Factory/ConfiguredDocumentMetadataFactory.php';

        return $container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.configured'] = new \ApiPlatform\Elasticsearch\Metadata\Document\Factory\ConfiguredDocumentMetadataFactory([]);
    }
}
