<?php

namespace ContainerWuQL70c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_ItemDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.item_data_provider' shared service.
     *
     * @return \ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\ItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Elasticsearch/DataProvider/ItemDataProvider.php';

        return $container->privates['api_platform.elasticsearch.item_data_provider'] = new \ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\ItemDataProvider(($container->privates['api_platform.elasticsearch.client'] ?? $container->load('getApiPlatform_Elasticsearch_ClientService')), ($container->privates['api_platform.elasticsearch.metadata.document.metadata_factory.cached'] ?? $container->load('getApiPlatform_Elasticsearch_Metadata_Document_MetadataFactory_CachedService')), ($container->privates['api_platform.elasticsearch.identifier_extractor'] ?? $container->load('getApiPlatform_Elasticsearch_IdentifierExtractorService')), ($container->privates['serializer'] ?? $container->getSerializerService()), ($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()));
    }
}
