<?php

namespace ContainerWuQL70c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Elasticsearch_Cache_Metadata_DocumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.elasticsearch.cache.metadata.document' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\AdapterInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.elasticsearch.cache.metadata.document'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('8j0cKSZgvh', 0, $container->getParameter('container.build_id'), ($container->targetDir.''.'/pools/system'), ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
    }
}
