<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuQL70c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuQL70c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWuQL70c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWuQL70c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWuQL70c\App_KernelDevDebugContainer([
    'container.build_hash' => 'WuQL70c',
    'container.build_id' => 'f73cd996',
    'container.build_time' => 1665396793,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuQL70c');
